config/routes.rb
Rails.application.routes.draw do
  root to: "flights#new"

  resources :airports
  resources :flights
end

app/models/airport.rb
class Airport
  attr_reader :icao, :name, :lat, :lng

  def initialize(icao, name, lat, lng)
    @icao = icao
    @name = name
    @lat = lat
    @lng = lng
  end

  def display_name
    "#{name} (#{icao})"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  AIRPORTS = [
    Airport.new("EGNT", "Newcastle"),
    Airport.new("EGLL", "Heathrow"),
    Airport.new("EGPH", "Edinburgh"),
    Airport.new("KBWI", "Baltimore"),
    Airport.new("KJFK", "JFK"),
    Airport.new("CYOW", "Ontario"),
    Airport.new("MMIA", "Colima")
  ]

  def index
    render "autocomplete/list", locals: {
      dom_id: params[:dom_id],
      entries: airports_matching(params[:q]),
      value: :icao,
      name: :display_name
    }
  end

  private

  def airports_matching(query)
    return [] if query.blank?

    AIRPORTS.filter do |airport|
      airport.name =~ /#{query}/i || airport.icao =~ /^#{query}/i
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def new
    @flight = Flight.new
  end

  def create
    @flight = Flight.create!(flight_params)
  end

  def index
    @flights = Flight.all.order(created_at: :desc)
  end

  private

  def flight_params
    params.require(:flight).permit(:departure_airport, :arrival_airport)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/autocomplete/list.turbo_stream.erb
<%= turbo_stream.update dom_id do %>
  <% if entries.empty? %>
    <div></div>
  <% else %>
    <div class="position-absolute d-grid bg-white border rounded w-100 mt-2 p-2" style="z-index: 9999;">
      <% entries.each do |entry| %>
        <button data-action="click->autocomplete#choose:prevent"
                data-autocomplete-value-param="<%= entry.public_send(value) %>"
                class="btn btn-link text-start">
          <%= entry.public_send(name) %>
        </button>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/flights/_flight_row.html.erb
<tr>
  <td><%= flight.departure_airport %></td>
  <td><%= flight.arrival_airport %></td>
  <td><%= flight.created_at %></td>
</tr>

app/views/flights/create.turbo_stream.erb
<%= turbo_stream.prepend :flights_list do %>
  <%= render "flights/flight_row", flight: @flight %>
<% end %>

app/views/flights/index.html.erb
<h1 class="mb-3">All Flights</h1>

<%= turbo_frame_tag :flights do %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Departing</th>
        <th>Arriving</th>
        <th>Booked at</th>
      </tr>
    </thead>

    <tbody id="flights_list">
      <%= render collection: @flights, partial: "flights/flight_row", as: :flight %>
    </tbody>
  </table>
<% end %>

app/views/flights/new.html.erb
<section class="mx-auto bg-white rounded p-3 mb-5">
  <h1 class="fs-6 font-medium text-uppercase text-center mb-3">Book a flight</h1>

  <%= form_for @flight, data: { controller: "validate" } do |f| %>
    <div class="row mb-3">
      <div class="col">
        <%= f.label :departure_airport, "Departing from", class: "form-label small" %>
        <%= f.text_field :departure_airport, class: "form-control", data: {
          "action": "input->validate#check",
          "validate-target": "departure"
        } %>
      </div>

      <div class="col">
        <%= f.label :arrival_airport, "Flying to", class: "form-label small" %>
        <%= f.text_field :arrival_airport, class: "form-control", data: {
          "action": "input->validate#check",
          "validate-target": "arrival"
        } %>
      </div>
    </div>

    <div class="row">
      <div class="col text-end">
        <%= f.submit "Find Flights", class: "btn btn-warning", disabled: true, data: { "validate-target": "button" } %>
      </div>
    </div>
  <% end %>
</section>

<section class="mx-auto">
  <h1 class="fs-5 font-medium">Recently Booked Flights</h1>

  <%= turbo_frame_tag :flights, src: flights_path %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">
    <header class="mb-5">
      <nav class="navbar bg-warning">
        <div class="container">
          <span class="navbar-brand mb-0 h1">queasyJet</span>

          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "Flights", flights_path, class: "nav-link" %></li>
          </ul>
        </div>
      </nav>
    </header>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>